### ISSUE TITLE
Initializing Docker for Mac

### ISSUE THREAD

**Issue by timsutton** [autopkg/chilcote-recipes#2]
FWIW, I just posted a basic working script on the Docker forum [here](https://forums.docker.com/t/feature-request-cli-tool-for-automated-installation/18334/5?u=timsutton). This could be adapted to either a Munki postinstall script or built into the pkg as a new postinstall script (and then use the pkg with Munki, JSS, etc. instead).

**Comment by chilcote** [comment]
Thanks Tim.  Added that in as a postinstall in the pkg recipe.

**Comment by timsutton** [comment]
`/Library/PrivilegedHelperTools` has the sticky bit on the (10.11) systems I've looked at, so if you're going to create it might as well also set mode `1755` on it and make sure it's owned by `root:wheel`.

Also if it's going to be used as part of a pkg installer, probably want to also use `$3` where appropriate.

**Comment by chilcote** [comment]
Ah right right.  Details. This will learn me to do this stuff when I'm in a hurry.
